name: Import open source standard labels

on:
  workflow_dispatch:
  schedule:
    - cron: '40 17 * * 4'

jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - uses: EddieHubCommunity/gh-action-open-source-labels@v0.6.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: ${{ github.repository_owner }}
        repository-name: ${{ github.event.repository.name }}
